selenium:
  default: true
  timeout: 10
  max_results: 5
  headless: true
  retry_attempts: 3
  retry_delay: 2
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  selectors:
    result_container: "div.g"
    title: "h3"
    link: "a"
    snippet: "div.VwiC3b"

serper:
  default: false
  max_results: 5
  timeout: 5
  retry_attempts: 2
  retry_delay: 1
  endpoints:
    search: "https://google.serper.dev/search"
    news: "https://google.serper.dev/news"
    places: "https://google.serper.dev/places"

mlflow:
  experiment_name: "search_performance_monitoring"
  metrics:
    - name: "search_time"
      unit: "seconds"
    - name: "results_count"
      unit: "count"
    - name: "success_rate"
      unit: "percentage"
  params:
    - "search_tool"
    - "query"
    - "max_results"
    - "timeout"

knowledge:
  storage:
    path: "search_results"
    format: "json"
    max_age_days: 7
  analysis:
    track_sources: true
    track_performance: true
    track_queries: true
